sonar.projectKey=optibroker-optibroker-common
sonar.projectName=optibroker-common
sonar.sources=optibroker_common
sonar.tests=tests
sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**
sonar.host.url=https://sonarqube.dev-op.co.uk
sonar.python.coverage.reportPaths=coverage.xml
